---
language: python
python: "2.7"

# Utiliza la nueva infraestructura de contenedores
sudo: false

# Instala ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Instala ansible
  - pip install ansible

  # Verifica la versión de ansible
  - ansible --version

  # Crea ansible.cfg con la ruta correcta de roles
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Comprobación básica de sintaxis del rol
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
